version: '3.7'
services:
  mysql-recrutement:
    image: mysql:8
    container_name: mysql-dev
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: recrutement
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
